name: Deploy to 2 EC2 instances

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to EC2_HOST_1
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST_1 }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "cloudproject"

    - name: Restart app on EC2_HOST_1
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST_1 }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd cloudproject
          npm install
          npm run build
          pm2 restart yourapp || pm2 start npm --name "yourapp" -- start
          pm2 save

    - name: Deploy to EC2_HOST_2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST_2 }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "cloudproject"

    - name: Restart app on EC2_HOST_2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST_2 }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd cloudproject
          npm install
          npm run build
          pm2 restart yourapp || pm2 start npm --name "yourapp" -- start
          pm2 save
